version: '3.3'
services:
  db:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress1
      MYSQL_USER: Jyothirmai
      MYSQL_PASSWORD: Jyothi@123

  wordpress:
    image: wordpress:latest
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress1
      WORDPRESS_DB_USER: Jyothirmai
      WORDPRESS_DB_PASSWORD: Jyothi@123

volumes:
  db_data: